source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'

def pods

# Utilities
swift_version = "3.0"
pod 'PromiseKit', '~> 4.0'

# Extensionsb
pod 'EZSwiftExtensions'

# Networking
pod 'Alamofire', '4.0.0'

# JSON
pod 'SwiftyJSON', :git => 'https://github.com/appsailor/SwiftyJSON.git', :branch => 'swift3'

# DB
pod 'MagicalRecord'

# swift integration
use_frameworks!

# who cares about warnings
inhibit_all_warnings!

end

target 'consumer' do
    pods
end
